/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

import Clases.ConexaoMySQL;

/**
 *
 * @author jeffley
 */
public class TbDados extends javax.swing.JFrame {

    /**
     * Creates new form TbDados
     */
    public TbDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void loadTabeladados(){
        RestTemplate reque = new RestTemplate();
        
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVisualizar = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projetos");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVisualizar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnCriar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnApagar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnApagar.setText("Apagar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnVisualizar)
                .addGap(62, 62, 62)
                .addComponent(btnCriar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(50, 50, 50)
                .addComponent(btnApagar)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizar)
                    .addComponent(btnCriar)
                    .addComponent(btnEditar)
                    .addComponent(btnApagar))
                .addGap(14, 14, 14))
        );

        btnImprimir.setBackground(new java.awt.Color(102, 102, 102));
        btnImprimir.setForeground(new java.awt.Color(0, 0, 153));
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(btnImprimir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        // Conectar ao banco de dados
        Connection conexao = ConexaoMySQL.conectar();

        // Consulta SQL para selecionar todos os dados da tabela planta
        String sql = "SELECT * FROM planta";

        // Criar uma instrução SQL
        try (PreparedStatement stmt = conexao.prepareStatement(sql)) {
            // Executar a consulta
            ResultSet rs = stmt.executeQuery();

            // Exibir os resultados (você pode ajustar esta parte conforme necessário)
            while (rs.next()) {
                String data = rs.getString("Data");
                String nome = rs.getString("Nome");
                String linha = rs.getString("Linha");
                String planta = rs.getString("Planta");
                String dadosBrix = rs.getString("DadosBrix");
                String dadosPressao = rs.getString("DadosPressao");
                String dadosMVerde = rs.getString("DadosMVerde");
                String dadosMseca = rs.getString("DadosMseca");

                // Faça algo com os dados, como exibi-los em uma caixa de diálogo
                String mensagem = "Data: " + data + "\nNome: " + nome + "\nLinha: " + linha +
                        "\nPlanta: " + planta + "\nDados Brix: " + dadosBrix +
                        "\nDados Pressão: " + dadosPressao + "\nDados Massa Verde: " + dadosMVerde +
                        "\nDados Massa Seca: " + dadosMseca;

                JOptionPane.showMessageDialog(this, mensagem, "Detalhes da Planta", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
    } catch (SQLException e) {
        // Lidar com exceções de banco de dados
        JOptionPane.showMessageDialog(this, "Erro ao recuperar dados da planta: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    private void btnImprimir(ActionEvent evt) {
        Connection conexao = null;

        try {
            // Estabelece a conexão com o banco de dados
            conexao = ConexaoMySQL.conectar();

            // Executa a consulta
            String sql = "SELECT Data, Nome, Linha, Planta, DadosBrix, DadosPressao, DadosMVerde, DadosMseca FROM planta";
            try (PreparedStatement stmt = conexao.prepareStatement(sql);
                 ResultSet resultSet = stmt.executeQuery()) {

                // Abre o arquivo para escrita
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("dados_planta.txt"))) {
                    // Escreve os cabeçalhos no arquivo
                    writer.write("Data\tNome\tLinha\tPlanta\tDadosBrix\tDadosPressao\tDadosMVerde\tDadosMseca");
                    writer.newLine();

                    // Itera sobre os resultados e escreve no arquivo
                    while (resultSet.next()) {
                        writer.write(resultSet.getString("Data") + "\t"
                                + resultSet.getString("Nome") + "\t"
                                + resultSet.getString("Linha") + "\t"
                                + resultSet.getString("Planta") + "\t"
                                + resultSet.getString("DadosBrix") + "\t"
                                + resultSet.getString("DadosPressao") + "\t"
                                + resultSet.getString("DadosMVerde") + "\t"
                                + resultSet.getString("DadosMseca"));
                        writer.newLine();
                    }
                }

                System.out.println("Consulta realizada com sucesso. Os dados foram salvos no arquivo dados_planta.txt.");
                JOptionPane.showMessageDialog(this, "Um arquivo txt foi gerado com sucesso ! " );
            }
        } catch (SQLException | IOException e) {
            e.printStackTrace();
        } 
    }
    
    

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        // TODO add your handling code here:
        PageTabela page = new PageTabela();
        
        page.setVisible(true);
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        PageTabelaEditar editar = new PageTabelaEditar();
        
        editar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TbDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TbDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TbDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TbDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TbDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class RestTemplate {

        public RestTemplate() {
        }
    }
}
